---
name: idr0155-fu-alphasynuclein/experimentA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: false
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split:
  # Should this column be included in the clients (yes/no)
  includeclient: true
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: true
  # Should empty values be omitted from the client display
  omitempty: true

columns:

  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: true

  - name: Characteristics [Diagnosis]
    clientname: Diagnosis
    include: true

  - name: Characteristics [Sex]
    include: Sex

  - name: Characteristics [Age]
    clientname: Age
    include: true

  - name: Comment [Number of Spots]
    clientname: Number of Spots
    include: true

  - name: Comment [Intensity of Spots]
    clientname: Intensity of Spots
    include: true

  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/antibody
      columns:
        - name: Experimental Condition [Antibody 1]
          clientname: Antibody Name
          include: true
          omitempty: true
        - name: Antibody Identifier 1
          clientname: Antibody Identifier
          include: true
          omitempty: true
        - name: Antibody Identifier 1
          clientname: Antibody Identifier URL
          clientvalue: https://antibodyregistry.org/{{ value|urlencode }}
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/antibody
      columns:
        - name: Experimental Condition [Antibody 2]
          clientname: Antibody Name
          include: true
          omitempty: true
        - name: Antibody Identifier 2
          clientname: Antibody Identifier
          include: true
          omitempty: true
        - name: Antibody Identifier 2
          clientname: Antibody Identifier URL
          clientvalue: https://antibodyregistry.org/{{ value|urlencode }}
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/antibody/supplementary
      columns:
        - name: Experimental Condition [Antibody 1]
          clientname: Antibody Name
          include: yes
          omitempty: no
        - name: Antibody Dilution 1
          clientname: Dilution Factor
          include: yes
          omitempty: no

  - group:
      namespace: openmicroscopy.org/mapr/antibody/supplementary
      columns:
        - name: Experimental Condition [Antibody 2]
          clientname: Antibody Name
          include: yes
          omitempty: no
        - name: Antibody Dilution 2
          clientname: Dilution Factor
          include: yes
          omitempty: no


advanced:
  ignore_missing_primary_key: true
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/antibody
      keys:
        - Antibody Name
        - Antibody Identifier
